pipeline {
    agent any
    stages {
        stage('Build and Run Docker Container') {
            steps {
                script {
                    // Seu comando docker run aqui
                    sh 'docker run -p 8082:8082 adriananogueira/calculator:1.0'
                }
            }
        }
    }
}
